### ISSUE TITLE
Is path to ssh hard-coded in scp?

### ISSUE THREAD

**Issue by scottidler** [ccontavalli/ssh-ident#13]
About scp, rsync, and friends
    =============================
    
    scp, rsync, and most similar tools internally invoke ssh. If you don't tell
    them to use ssh-ident instead, key loading won't work. There are two simple
    ways to solve the problem:
    
    1) Rename 'ssh-ident' to 'ssh' or create a symlink 'ssh' pointing to
       ssh-ident in a directory in your PATH before /usr/bin or /bin, similarly
       to what was described previously. For example, add to your .bashrc:
    
        export PATH="~/bin:$PATH"
        ln -s /path/to/ssh-ident ~/bin/ssh
    
       Make sure `echo $PATH` shows '~/bin' *before* '/usr/bin' or '/bin'. You
       can verify this is working as expected with `which ssh`, which should
       show ~/bin/ssh.

----------------------------------------------------------------------------------------------------------------------------------------

Regarding above, has anyone tested if this works?  I have a symlink:
    **/usr/local/bin/ssh -> ~/repos/ccontavalli/ssh-ident/ssh-ident**

This works great for ssh but gives **"Permission denied (publickey,keyboard-interactive)"** when trying to scp to the same server.I believe this is because scp isn't using **/usr/local/bin/ssh** even though this appears before **/usr/bin/ssh** in my path.  Trying `which ssh` returns my symlink, **/usr/local/bin/ssh**.  However, prefixing **BINARY_SSH=scp /usr/local/bin/ssh** does work as expected.  This caused me to look at the source for scp:  
    https://github.com/openssh/openssh-portable/search?utf8=%E2%9C%93&q=_PATH_SSH_PROGRAM

As you can see, it appears as though scp hard-codes **/usr/bin/ssh**.  This would explain the symptoms I am seeing.  Of course, I could have missed something or be mistaken.

I love this tool, but it is currently blocking my ability to scp.

Respectfully,
Scott

$ uname -a
Linux xps 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~ 
$ /usr/bin/ssh -V
OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015
~ 
$ (cd ~/repos/ccontavalli/ssh-ident && git rev-parse HEAD)
bc00a5919b2d5a3ff6d677460e840f58c2534c7f

**Comment by scottidler** [comment]
Not real excited about the lack of response on issues, but here is the script I wrote that works around the issue:

```
$ cat /usr/local/bin/scp 
#!/bin/bash
exec env BINARY_SSH=/usr/bin/scp /usr/local/bin/ssh "$@"
```

**Comment by black2754** [comment]
This issue has been vexing me for quite some time, too.

You are right. Unlike `rsync` and `git`, for instance, `scp` calls the real `ssh` instead of the symlink to `ssh-ident`, thus completely bypassing it.

A script like yours or a shell alias makes `scp` work with `ssh-ident`.
However, I believe the *proper* fix would be for `ssh-ident` to automatically detect the name under which it was called, find that binary in the `PATH` and run it. Then you could simply add a symlink named `scp` (and/or `sftp`) that points to `ssh-ident` and be done.
Maybe I'll finally get around implementing that and sending a pull request in the next few days...

**Comment by ccontavalli** [comment]
Hello - sorry for latency, and thanks for reporting the issue with the hard coded path in the first place.
I very rarely use scp, default to rsync, and had not noticed the problem.

I have merged in black2754 change finally, and verified it is working as expected.

Additionally, there is now a new parameter in the config, BINARY_DIR. The idea is that if argv[0] is 'scp' or '/usr/local/bin/scp', and BINARY_DIR is set to "/usr/bin", ssh-ident will look for a binary to run named "/usr/bin/scp".

The default, though, is now the autodetection code that black2754 has added.

**Comment by scottidler** [comment]
Nice job and much appreciated!
