### ISSUE TITLE
Convert README to Markdown

### ISSUE THREAD

**Issue by chrisfinazzo** [ccontavalli/ssh-ident#17]
Is there a reason you chose "Software Package Notes"? My apologies in advance, I'm not well-versed with Python or Debian to know whether or not this is standard practice. If the idea is appealing, I will submit a PR for this and #16.

**Comment by ccontavalli** [comment]
Today, I generate the README by using the command "pydoc ./ssh-ident", this extracts the comments from the .py file, and generates the man page and README.

There was at least another issue raised a month or two ago mentioning that the documentation could be clearer and better formatted. So I'm all for it :) if you have time, that'd be great.

Sorry it took me a while to get back to you. Thanks!

**Comment by kominoshja** [comment]
Just came across this after submitting https://github.com/ccontavalli/ssh-ident/pull/64 :)

**Comment by chrisfinazzo** [comment]
@kominoshja This was on my list for a long time, I guess it just fell off the radar. Thanks for picking it up.
