### ISSUE TITLE
Loop by invoking the latest ssh-ident

### ISSUE THREAD

**Issue by ktsamis** [ccontavalli/ssh-ident#21]
I downloaded the latest version of the script with git clone, I created an alias in my bashrc, tried to connect to a host with ssh and I get:

ssh-ident found 'ssh-ident' as the next command to run.
Based on argv[0] (/suse/ktsamis/Git/ssh-ident/ssh-ident), it seems like this will create a
loop. 

Please use BINARY_SSH, BINARY_DIR, or change the way
ssh-ident is invoked (eg, a different argv[0]) to make
it work correctly.

So it seems something was broken?

**Comment by mc0e** [comment]
At one point in setting up I had both a symlink in my `~/bin` directory and an alias.  That gave similar results to what you are seeing.

I prefer putting a symlink at `~/bin/ssh` (and likewise for scp and rsync) and not using aliases.

**Comment by ktsamis** [comment]
I completely removed every setting I had (alias, removed the script from everywhere) and went back to plain old ssh. I redownload ssh-ident with:
       mkdir -p ~/bin; wget -O ~/bin/ssh goo.gl/MoJuKB; chmod 0755 ~/bin/ssh
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc

I confirm that it is used with: which ssh -> ~/bin/ssh
And I still get the error. I tried with all sort of options, symlink to the local git copy, alias and I still get the same. I don't think I have a wrong combination because I completely removed it.

**Comment by ktsamis** [comment]
Ok, I have no idea what I did differently now but it works. Maybe I forgot to source my bashrc or something? Sorry for the noise. This issue can now be closed.

**Comment by cwallsfdc** [comment]
Same issue for me.

**Comment by maddes-b** [comment]
Typically this is a problem in the setup, either environment or using multiple ssh-ident symlinks for an binary.

- Check that there are no duplicate dirs in your ${PATH}, e.g. twice the $[HOME}/bin.
  - Note that duplicates can also occur through symlinks as a different dir/path.
- Check that there is only one ssh-ident symlink in your ${PATH}, e.g. avoid symlink duplicates like ${HOME}/bin/scp and /usr/local/bin/scp
- When using symlinks for a binary, then do not use shell alias - and vice-versa
  - The approach can be different per binary
- BINARY_DIR is a hard-coded workaround, should not be necessary when setup is clean
