### ISSUE TITLE
ssh-ident doesn't work with ssh's `-M` option

### ISSUE THREAD

**Issue by mc0e** [ccontavalli/ssh-ident#23]
I use ssh's `ControlMaster` and associated configuration in order to get re-use of ssh connections for fast session startup.

It seems that when ssh is aliased to ssh-ident, then `ssh -M server` fails to use the right agent.  It loads keys as expected in the correct agent, but then fails to use the existing connection or the ssh-agent that I'd expect it to use.  The connection fails since the required key is not available.

This makes a huge difference to me, as some of my routine operations involve running hundreds of ssh commands over ssh from a single scripted operation.

**Comment by mc0e** [comment]
I may have a broader problem.  Without the `-M` option, I'm seeing similar failures to offer the keys as expected.

**Comment by mc0e** [comment]
I have found an issue, but it's not as described.  This ticket can close.

**Comment by ccontavalli** [comment]
ok, closing as recommended :)
