### ISSUE TITLE
exporting path using ~ might not work on certain systems

### ISSUE THREAD

**Issue by McKean** [ccontavalli/ssh-ident#38]
Hey there, thanks for this awesome tool, I struggled setting up the symbolic link and exporting my path using
`'export PATH=~/bin:$PATH'`
instead I had to use $HOME/bin

just my two cents.

**Comment by maddes-b** [comment]
I agree using ${HOME} is more portable and not dependent on the shell functionality.
Will change this in my fork at https://github.com/maddes-b/ssh-ident

**Comment by McKean** [comment]
It's been a while :)

**Comment by maddes-b** [comment]
Fork moved to https://github.com/ssh-ident/ssh-ident1
