### ISSUE TITLE
SSH_DEFAULT_OPTIONS causes grief with rsync

### ISSUE THREAD

**Issue by fbicknel** [ccontavalli/ssh-ident#41]
There's a couple of places in the code where `SSH_DEFAULT_OPTIONS` is set to no. That's great for _ssh_ and _scp_, but _rsync_ barks at it.

```
$ rsync -avrz --dry-run foohost:FLMPOC/ .
All keys already loaded
rsync: -oUseRoaming=no: unknown option
rsync error: syntax or usage error (code 1) at main.c(1572) [client=3.1.1]
$ 
```

I found a workaround by setting `SSH_DEFAULT_OPTIONS=''` on the command line when using _rsync_:

`alias rsync='SSH_DEFAULT_OPTIONS= BINARY_SSH=rsync /usr/local/bin/ssh-ident'
`

**Comment by Jamesking56** [comment]
Possible duplicate of #24

**Comment by fbicknel** [comment]
Might be duplicate-adjacent, I admit. But it's a whole lot more succinct. :)

**Comment by maddes-b** [comment]
The fork at https://github.com/ssh-ident/ssh-ident1 allows to define ssh options per identity and binary.
