### ISSUE TITLE
How to remember password key after reboot

### ISSUE THREAD

**Issue by sanekmihailow** [ccontavalli/ssh-ident#47]
I have ente the password for my private key after reboot pc. How to save my password private key after reboot?, like this:

$ ssh bhh@bhost  -p1234
(without enter password priv key after executing command)

**Comment by jackm** [comment]
I'm not certain how to force it to remember the key passphrase but I would advise against this. The whole point of having a passphrase for a key file is for additional security. If you don't need this extra layer of security or are too annoyed by it, then I would suggest just remove the passphrase from the key file entirely.

**Comment by sanekmihailow** [comment]
Sorry, but it not a solution. Now i use keychain, he is more useful.
