### ISSUE TITLE
Silence "All keys already loaded"

### ISSUE THREAD

**Issue by HaleTom** [ccontavalli/ssh-ident#52]
Is the message: `All keys already loaded` really necessary? 

It's being printed to STDERR, but it's not an error, as [it has `loglevel=LOG_INFO`](https://github.com/ccontavalli/ssh-ident/blob/master/ssh-ident#L699):

Some things which check for a non-empty STDERR stream may get confused by this, too.

Perhaps only enable it when given a verbose `-v`?

Or (less preferred), quieten it with a `-q`?

**Comment by HaleTom** [comment]
I'd suggest just disabling:

If allowing a `-v` or `-q`, then there would need to be a mandatory `--` delimiter afterwards also to distinguish from any options passed through to the `$BINARY_SSH` command itself.

(`ssh` also supports `-v` for instance)

**Comment by HaleTom** [comment]
Actually, it seems it's not being output to STDERR, but directly to `/dev/tty`:
```
% binary=ssh ssh-ident localhost &>/dev/null
All keys already loaded
%
```

I find this message to be as annoying as the town crier ringing his bell and shouting through the streets:

> "3am and all is well"

How can I disable `All keys already loaded`?

**Comment by jackm** [comment]
Just change the output verbosity by setting `VERBOSITY` in the ssh-ident config file to something less verbose than LOG_INFO. This is in the README under "Config file with multiple identities" section 1.

eg. `VERBOSITY = LOG_WARN`

**Comment by HaleTom** [comment]
Excellent! Thank you!
