### ISSUE TITLE
multiple keys per identity?

### ISSUE THREAD

**Issue by jnorell** [ccontavalli/ssh-ident#6]
I have setup multiple identities, and trying to setup one with two key pairs.  Per the instructions, *All files in your identities subdirectories will be considered keys.*  I had filenames of 2011-id_rsa{,.pub} and 2014-id_rsa{,.pub}, and it didn't find any keys, saying:

    Warning: no keys found for identity personal in:
    ['/home/user/.ssh/identities/personal']

I renamed one set of keys to just id_rsa{,.pub} and it then loaded them.  Is there a restriction on filenames here, or ??  I may be able to specify multiple keys per host with IdentityFile setting, though that's certainly not ideal.

Thanks....

**Comment by ccontavalli** [comment]
Marking this as closed, I assume this worked for you :) let me know if you still have problems.

**Comment by stefanmohl** [comment]
I hit this problem too; perhaps re-open the bug as a bug in the documentation?

**Comment by HaleTom** [comment]
I just bumped into this problem too. +1 for documenting it.
